function input_scaling_factor_uV = get_input_scaling_factor_uV(Hw)

% InputScalingFactor_uV = 10^(2/20)/1e4*2*sqrt(2)/1e-6;
input_scaling_factor_uV = 1/(Hw.PhysAmp_GainFactor ...
                          * Hw.SoundCard_In_Impedance/(Hw.SoundCard_In_Impedance+Hw.PhysAmp_Out_Impedance) ...
                          * Hw.SoundCardVoltToSamplePeak) ...
                          /1e-6;
