function mic_scaling_Pa = get_mic_scaling_Pa(Hw)

% mic_scaling_Pa = 2e-5/1e-6*10^(2/20);
if isempty(Hw.Mic_Cal_Value)
    mic_scaling_Pa = 1/(2e-5 * Hw.Mic_PascalToVoltRMS ...
                             * Hw.MicAmp_In_Impedance/(Hw.MicAmp_In_Impedance+Hw.Mic_Out_Impedance) ...
                             * Hw.MicAmp_GainFactor ...
                             * Hw.SoundCard_In_Impedance/(Hw.SoundCard_In_Impedance+Hw.MicAmp_Out_Impedance) ...
                             * Hw.SoundCardVoltToSampleRMS);
else
    mic_scaling_Pa = 10^(Hw.Mic_Cal_Value/20);
end             